environments:
  default:
    values:
    - registry:
        provider: ghcr.io/pampatzoglou
        username: {{ requiredEnv "REGISTRY_USER"}}
        password: {{ requiredEnv "REGISTRY_PAT" }}
        email:    devops+api@foo.ddd
    - mongo:
        enabled: true
        connector:  mongodb://{{ requiredEnv "MONGODB_USERNAME" }}:{{ requiredEnv "MONGODB_PASSWORD" }}@mongo-mongodb:27017/db