---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graph.fullname" . }}-registrykey
  namespace: {{ .Release.Namespace | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "graph.fullname" . }}-mongo
    namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  connector: {{ .Values.mongo.connector | default "mongodb://mongo:27017/db" | b64enc }}