bases:
- ../../environments.yaml

helmDefaults:
  createNamespace: true
  wait: true
  timeout: 120

repositories:
- name: bitnami
  url:  https://charts.bitnami.com/bitnami

releases:
- name: mongo
  namespace: api
  chart:     bitnami/mongodb
  version:   12.1.20
  labels:
    app: api
    tier: backend
    type: database
  condition: mongo.enabled
  values:
  - config/mongo/mongo-values.yaml
  - config/mongo/mongo-{{ .Environment.Name }}-values.yaml.gotmpl