bases:
- ../../environments.yaml

helmDefaults:
  createNamespace: true
  wait: true

repositories:
- name: bitnami
  url:  https://charts.bitnami.com/bitnami

releases:
- name: mongo
  namespace: graph
  chart:     bitnami/mongodb
  version:   12.1.20
  labels:
    app: mongo
  condition: mongo.enabled