bases:
- ../../environments.yaml

helmDefaults:
  createNamespace: true
  wait: true
  timeout: 120

releases:
- name: graph
  namespace: api
  chart: ../helm/
  labels:
    app: api
    tier: backend
    type: service
  values:
  - config/graph/graph-values.yaml.gotmpl