name: default
on:
  push:
    branches:
    - "*"
jobs:
  KinD:
    strategy:
      matrix:
        environments: ["default"]
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: 1.18
      - name: Install latest version of Kind
        run: |
          GO111MODULE=on go get sigs.k8s.io/kind
      - name: Create Kind cluster
        run: |
          PATH=$(go env GOPATH)/bin:$PATH kind create cluster --config kind-config.yaml
      - name: Run some sanity checks
        # kubectl is already installed on the Github Ubuntu worker
        run: |
          kubectl get nodes -o wide
          kubectl get pods --all-namespaces -o wide
          kubectl get services --all-namespaces -o wide
      #- name: Setup tmate session
        #if: ${{ RUNNER_DEBUG }}=="1"
      #  uses: mxschmitt/action-tmate@v3