name: default
on:
  push:
    branches:
    - "*"
jobs:
  KinD:
    strategy:
      matrix:
        environments: ["default"]
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Kind for ${{ matrix.environments }} environment
        uses: engineerd/setup-kind@v0.5.0
      - name: Setup tmate session
        if: ${{ env.RUNNER_DEBUG }}=="1"
        uses: mxschmitt/action-tmate@v3